version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
